#!/usr/bin/python3

# import sys

print('Калькулятор подсчёта стоимости бензина приветствует.\n'
      'NB! Дробные числа надо вводить через точку.')

gas_prise = 46.50
user_input = input('Стоимость 1 л бензина - {} руб. '
                   'Изменить (y/n)?'.format(gas_prise))
if user_input == 'y' or user_input == 'н':
    gas_prise = float(input('Новая стоимость: '))
    print('Подтверждаю, стоимость теперь {} руб.'.format(gas_prise))
    # path_to_this_file = sys.argv[0]
    # with open(path_to_this_file, 'w') as f:

while True:
    mileage = float(input('Пробег, км: '))
    gas_usage = float(input('Расход бензина, л на 100 км: '))

    # за 100 км расходуется gas_usage бензина
    # за mileage км расходуется x бензина

    gas_cost = round(mileage * gas_usage / 100 * gas_prise)
    user_input = input('Израсходовано бензина на {} руб.'
                       '\nЕщё итерацию? (y/n)'.format(str(gas_cost)))
    if user_input == 'n' or user_input == 'т':
        print('OK, калькулятор подсчёта стоимости бензина прощается.')
        break
    else:
        continue
